package com.isoler.studynav.business.link.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.baomidou.mybatisplus.core.metadata.IPage;
import com.isoler.studynav.business.fl.model.qo.FlQo;
import com.isoler.studynav.business.link.model.bean.Link;
import com.isoler.studynav.business.link.model.qo.LinkQo;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * <p>
 * 网址链接 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
public interface LinkMapper extends BaseMapper<Link> {
    /**
     * 获取分类列表
     *
     * @param qo
     * @return
     */
    List<Link> listLink(@Param("qo") LinkQo qo);

    /**
     * 获取分类列表-分页
     *
     * @param qo
     * @return
     */
    List<Link> listLink(IPage<Link> page, @Param("qo") FlQo qo);

    /**
     * 设置最大序号
     *
     * @param id
     */
    void updateMaxXh(@Param("id") String id);
}
