package com.isoler.studynav.business.link.mapper;

import com.isoler.studynav.business.link.model.bean.Link;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 网址链接 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
public interface LinkMapper extends BaseMapper<Link> {

}
