package com.isoler.studynav.business.fl.mapper;

import com.isoler.studynav.business.fl.model.bean.Fl;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;

/**
 * <p>
 * 网址分类 Mapper 接口
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
public interface FlMapper extends BaseMapper<Fl> {

}
