package com.isoler.studynav.business.fl.service.impl;

import com.isoler.studynav.business.fl.model.bean.Fl;
import com.isoler.studynav.business.fl.mapper.FlMapper;
import com.isoler.studynav.business.fl.service.IFlService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 网址分类 服务实现类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Service
public class FlServiceImpl extends ServiceImpl<FlMapper, Fl> implements IFlService {

}
