package com.isoler.studynav.business.fl.model.bean;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.isoler.studynav.business.link.model.bean.Link;
import com.isoler.studynav.common.model.bean.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

import java.util.List;

/**
 * <p>
 * 网址分类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("db_nav.t_fl")
@ApiModel(value = "Fl对象", description = "网址分类")
public class Fl extends BaseEntity {


    @ApiModelProperty(value = "父分类id")
    @TableField("c_parent_id")
    private String parentId;

    @ApiModelProperty(value = "分类名称")
    @TableField("c_name")
    private String name;

    @ApiModelProperty(value = "分类描述")
    @TableField("c_description")
    private String description;

    @ApiModelProperty(value = "图标")
    @TableField("c_icon")
    private String icon;

    @ApiModelProperty(value = "排序")
    @TableField("n_order")
    private Integer xh;

    @ApiModelProperty(value = "网址列表")
    @TableField(exist = false)
    private List<Link> links;


}
