package com.isoler.studynav.business.fl.service;

import com.isoler.studynav.business.fl.model.bean.Fl;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 网址分类 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
public interface IFlService extends IService<Fl> {

}
