package com.isoler.studynav.business.link.service.impl;

import com.isoler.studynav.business.link.model.bean.Link;
import com.isoler.studynav.business.link.mapper.LinkMapper;
import com.isoler.studynav.business.link.service.ILinkService;
import com.baomidou.mybatisplus.extension.service.impl.ServiceImpl;
import org.springframework.stereotype.Service;

/**
 * <p>
 * 网址链接 服务实现类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Service
public class LinkServiceImpl extends ServiceImpl<LinkMapper, Link> implements ILinkService {

}
