package com.isoler.studynav.business.fl.controller;


import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RestController;

/**
 * <p>
 * 网址分类 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@RestController
@RequestMapping("fl")
public class FlController {

}
