package com.isoler.studynav.business.fl.controller;


import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.isoler.studynav.business.fl.model.bean.Fl;
import com.isoler.studynav.business.fl.model.qo.FlPageQo;
import com.isoler.studynav.business.fl.model.qo.FlQo;
import com.isoler.studynav.business.fl.service.IFlService;
import com.isoler.studynav.common.api.CommonResult;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import javax.validation.Valid;
import java.util.List;

/**
 * <p>
 * 网址分类 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Api(tags = "分类接口")
@RestController
@RequestMapping("fl")
public class FlController {

    @Resource
    private IFlService flService;

    @ApiOperation("分类列表")
    @PostMapping("list")
    public CommonResult<List<Fl>> listFl(@RequestBody @Valid FlQo qo) {
        return CommonResult.success(flService.listFl(qo));
    }

    @ApiOperation("分类列表-包含链接")
    @PostMapping("all")
    public CommonResult<List<Fl>> listRecFl(@RequestBody @Valid FlQo qo) {
        return CommonResult.success(flService.listFlRec(qo));
    }

    @ApiOperation("分类列表-分页")
    @PostMapping("page")
    public CommonResult<Page<Fl>> pageFl(@RequestBody @Valid FlPageQo qo) {
        return CommonResult.success(flService.pageFl(qo));
    }

    @ApiOperation("删除分类")
    @DeleteMapping("{id}")
    public CommonResult<String> deleteFl(@PathVariable("id") String id) {
        flService.deleteFlById(id);
        return CommonResult.success("删除成功");
    }

    @ApiOperation("新增或编辑分类")
    @PostMapping("")
    public CommonResult<Fl> saveOrUpdateFl(@RequestBody Fl fl) {
        return CommonResult.success(flService.saveOrUpdateFl(fl));
    }


    @ApiOperation("查看分类")
    @GetMapping("{id}")
    public CommonResult<Fl> viewFl(@PathVariable("id") String id) {
        return CommonResult.success(flService.getById(id));
    }

}
