package com.isoler.studynav.business.link.service;

import com.isoler.studynav.business.link.model.bean.Link;
import com.baomidou.mybatisplus.extension.service.IService;

/**
 * <p>
 * 网址链接 服务类
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
public interface ILinkService extends IService<Link> {

}
