package com.isoler.studynav.business.link.controller;


import org.springframework.web.bind.annotation.RequestMapping;

import org.springframework.web.bind.annotation.RestController;

/**
 * <p>
 * 网址链接 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@RestController
@RequestMapping("link")
public class LinkController {

}
