package com.isoler.studynav.business.link.controller;


import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import com.isoler.studynav.business.link.model.bean.Link;
import com.isoler.studynav.business.link.model.qo.LinkPageQo;
import com.isoler.studynav.business.link.model.qo.LinkQo;
import com.isoler.studynav.business.link.service.ILinkService;
import com.isoler.studynav.common.api.CommonResult;
import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import org.springframework.web.bind.annotation.*;

import javax.annotation.Resource;
import javax.validation.Valid;
import java.util.List;

/**
 * <p>
 * 网址链接 前端控制器
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Api(tags = "网址接口")
@RestController
@RequestMapping("link")
public class LinkController {

    @Resource
    private ILinkService linkService;

    @ApiOperation("网址列表")
    @PostMapping("list")
    public CommonResult<List<Link>> listFl(@RequestBody @Valid LinkQo qo) {
        return CommonResult.success(linkService.listLink(qo));
    }

    @ApiOperation("网址列表-分页")
    @PostMapping("page")
    public CommonResult<Page<Link>> pageFl(@RequestBody @Valid LinkPageQo qo) {
        return CommonResult.success(linkService.pageLink(qo));
    }

    @ApiOperation("删除网址")
    @DeleteMapping("{id}")
    public CommonResult<String> deleteLink(@PathVariable("id") String id) {
        linkService.deleteFlById(id);
        return CommonResult.success("删除成功");
    }

    @ApiOperation("新增或编辑网址")
    @PostMapping("")
    public CommonResult<Link> saveOrUpdateLink(@RequestBody Link link) {
        return CommonResult.success(linkService.saveOrUpdateLink(link));
    }


    @ApiOperation("查看网址")
    @GetMapping("{id}")
    public CommonResult<Link> viewLink(@PathVariable("id") String id) {
        return CommonResult.success(linkService.getById(id));
    }

    @ApiOperation("上移")
    @PutMapping("up/{id}")
    public CommonResult<String> moveUpLink(@PathVariable("id") String id) {
        linkService.moveUp(id);
        return CommonResult.success("移动成功");
    }

    @ApiOperation("下移")
    @PutMapping("down/{id}")
    public CommonResult<String> moveDownLink(@PathVariable("id") String id) {
        linkService.moveDown(id);
        return CommonResult.success("移动成功");
    }

}
