package com.isoler.studynav.business.link.model.bean;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import com.isoler.studynav.common.model.bean.BaseEntity;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * <p>
 * 网址链接
 * </p>
 *
 * @author AutoGenerated
 * @since 2022-10-08
 */
@Data
@EqualsAndHashCode(callSuper = false)
@Accessors(chain = true)
@TableName("db_nav.t_link")
@ApiModel(value = "Link对象", description = "网址链接")
public class Link extends BaseEntity {


    @ApiModelProperty(value = "所属分类id")
    @TableField("c_fl_id")
    private String flId;

    @ApiModelProperty(value = "网址名称")
    @TableField("c_name")
    private String name;

    @ApiModelProperty(value = "logo")
    @TableField("c_logo")
    private String logo;

    @ApiModelProperty(value = "网址描述")
    @TableField("c_description")
    private String description;

    @ApiModelProperty(value = "网址链接地址")
    @TableField("c_url")
    private String url;

    @ApiModelProperty(value = "阅读点击次数")
    @TableField("n_read")
    private Integer read;

    @ApiModelProperty(value = "网址链接的点赞次数")
    @TableField("n_star")
    private Integer star;

    @ApiModelProperty(value = "网址排序")
    @TableField("n_order")
    private Integer xh;

    @ApiModelProperty(value = "分类名称")
    @TableField(exist = false)
    private String flName;


}
